/*******************************************************************************
*                                                       ,----,                 *
*                                                     .'   .' \                *
*                                                   ,----,'    |               *
*               ________  ___       ________        |    :  .  ;               *
*              |\   ___ \|\  \     |\   ____\       ;    |.'  /                *
*              \ \  \_|\ \ \  \    \ \  \___|_      `----'/  ;                 *
*               \ \  \ \\ \ \  \    \ \_____  \       /  ;  /                  *
*                \ \  \_\\ \ \  \____\|____|\  \     ;  /  /-,                 *
*                 \ \_______\ \_______\____\_\  \   /  /  /.`|                 *
*                  \|_______|\|_______|\_________\./__;      :                 *
*                                     \|_________||   :    .'                  *
*                                                 ;   | .'                     *
*                                                 `---'                        *
********************************************************************************
* Author:            Hendrik de Bruin                                          *
* Maintainer:        Hendrik de Bruin                                          *
* author email:      hendrik.debruin@iit.it                                    *
*******************************************************************************/
#ifndef CONTROLLER_HPP_RSFU8GQS
#define CONTROLLER_HPP_RSFU8GQS

// =============================================================================
// Includes
// =============================================================================
#include "application_framework/components/periodic_app_layer_component.hpp"
#include "gait_generator/gait_signal.hpp"
#include "controller/control_signal.hpp"
#include "fastrtps_wrappers/blind_state.hpp"
#include "robot/robot.hpp"
#include "util/messaging/subscriber_base.hpp"
#include "util/messaging/publisher_base.hpp"
#include "msg/gait_signalPubSubTypes.h"
#include "msg/control_signalPubSubTypes.h"
#include "msg/blind_statePubSubTypes.h"

#include <chrono>
#include <string>
#include <memory>
#include <atomic>

// =============================================================================
// Class Interface
// =============================================================================
TODO("a lot of functions have been removed from Controller. Many of them need to be put into Dog")
namespace dls
{
class Controller : public PeriodicAppLayerComponent
{
	friend class ControlLayer;
	friend class GaitListener;
	friend class BlindStateListener;
public:
	// using ID_t = std::string;

	// Plugin typedefs
	typedef Controller *create_t();
	typedef void destroy_t(Controller*);

	Controller
	(
		const std::shared_ptr<Dog>&,						///< A pointer to the robot model
		const ID_t&,										///< The ID of the controller
		const period_t&,									///< The period of the controller
		const ControlSignal::SignalReconstructionMethod&	///< Signal reconstruction used by this controller
	);

	virtual ~Controller() = default;

	// This will be replaced by the shutdown and eStop functions
	TODO("unknown what this should do")
	// virtual void kill() = 0;

	///// Get the ID of this controller
	/////
	///// @ret the ID
	//ID_t getID() const;

	/// Returns the name of the topic where this controller is publishing its
	/// control signal
	std::string getControlSignalTopic() const;

protected:
	///// Function gets called each epoch.
	/////
	///// @param time The time when this function is called,
	//virtual void run(const std::chrono::system_clock::time_point &time) = 0;

	/// Gets the current value of the signal generated by the active gait
	/// generator
	std::shared_ptr<const GaitSignal> readGaitSignal() const;
	
	std::shared_ptr<BlindState> readBlindStateSignal() const;

	/// Sends the control command to the rest of the architecture
	void publishSignal(const ControlSignal&);

	const std::shared_ptr<const Dog> pDog;
	const std::string name;
	const ControlSignal::SignalReconstructionMethod signal_reconstruction_method;
	// const ID_t ID;

private:
	// BEGIN critical section
		/// The last reading of the signal from the current active gait generator
		std::shared_ptr<const GaitSignal> pGait_signal;
		mutable std::mutex gait_signal_mutex;
	// END critical section


	// BEGIN critical section
		std::shared_ptr<const ControlSignal> pControl_signal;
		mutable std::mutex control_signal_mutex;
	// END critical section
		
	// BEGIN critical section
		std::shared_ptr<BlindState> pBlind_state_signal;
		mutable std::mutex blind_state_signal_mutex;
	// END crital section

	std::atomic_bool should_run;

	// =============================== FastRTPS ================================
	class GaitListener : public SubscriberBase<GaitSignalMsgPubSubType>
	{
	public:
		GaitListener(std::shared_ptr<Controller>);
		~GaitListener() = default;
		void onNewDataMessage(eprosima::fastrtps::Subscriber*) override;
	private:
		const std::shared_ptr<Controller> pOwner;
		eprosima::fastrtps::SampleInfo_t info;
	} gait_listener;

	class BlindStateListener : public SubscriberBase<BlindStateMsgPubSubType>
	{
	public:
		BlindStateListener(std::shared_ptr<Controller>);
		~BlindStateListener() = default;
		void onNewDataMessage(eprosima::fastrtps::Subscriber*) override;
	private:
		const std::shared_ptr<Controller> pOwner;
		eprosima::fastrtps::SampleInfo_t info;
	} blind_state_listener;
	
	

	const std::string control_signal_topic;
	PublisherBase<ControlSignalMsgPubSubType> publisher;
};
} // end namespace dls

#endif /* end of include guard: CONTROLLER_HPP_RSFU8GQS */
