#ifndef CONTROLLER_HPP_RSFU8GQS
#define CONTROLLER_HPP_RSFU8GQS

// =============================================================================
// Includes
// =============================================================================
#include "application_framework/components/periodic_app_layer_component.hpp"
#include "gait_generator/gait_signal.hpp"
#include "controller/control_signal.hpp"
#include "robot/robot.hpp"

#include <chrono>
#include <string>
#include <memory>
#include <atomic>

// fastrtps
#include <fastrtps/fastrtps_fwd.h>
#include <fastrtps/subscriber/SubscriberListener.h>
#include <fastrtps/subscriber/SampleInfo.h>
#include "msg/hello_worldPubSubTypes.h"

// =============================================================================
// Class Interface
// =============================================================================
TODO("a lot of functions have been removed from Controller. Many of them need to be put into Dog")
class Controller : public PeriodicAppLayerComponent
{
	friend class ControlLayer;
	friend class SubListener;
public:
	using ID_t = std::string;

	// Plugin typedefs
	typedef Controller *create_t();
	typedef void destroy_t(Controller*);

	Controller
	(
		const std::shared_ptr<Dog>&,						///< A pointer to the robot model
		const ID_t&,										///< The ID of the controller
		const period_t&,									///< The period of the controller
		const ControlSignal::SignalReconstructionMethod&	///< Signal reconstruction used by this controller
	);

	virtual ~Controller() = default;

	// This will be replaced by the shutdown and eStop functions
	TODO("unknown what this should do")
	// virtual void kill() = 0;

	/// Get the ID of this controller
	///
	/// @ret the ID
	ID_t getID() const;

	/// Returns the current value of the control signal generated by this
	/// controller
	///
	/// @ret a shared pointer to ControlSignal
	const std::shared_ptr<const ControlSignal> readSignal() const;

protected:
	///// Function gets called each epoch.
	/////
	///// @param time The time when this function is called,
	//virtual void run(const std::chrono::system_clock::time_point &time) = 0;

	/// Gets the current value of the signal generated by the active gait
	/// generator
	std::shared_ptr<const GaitSignal> readGaitSignal() const;

	/// Sends the control command to the rest of the architecture
	void publishSignal(const std::shared_ptr<const ControlSignal>&);

	const std::shared_ptr<const Dog> pDog;
	const std::string name;
	const ControlSignal::SignalReconstructionMethod signal_reconstruction_method;
	const ID_t ID;

private:
	/// Makes the controller aware of the last known reading from the gait
	/// generator
	///
	/// This function should only be called from the ControlLayer The controller
	/// does not read the signal from a member in ControlLayer.  Instead, the
	/// ControlLayer pushes the signal here. This is done since multiple
	/// controllers can be active at the same time. We want each controller to
	/// receive the same synchronised signal at the end of the epoch of the gait
	/// generator.
	void pushSignal(const std::shared_ptr<GaitSignal>&);

	// BEGIN critical section
		/// The last reading of the signal from the current active gait generator
		std::shared_ptr<GaitSignal> pGait_signal;
		mutable std::mutex gait_signal_mutex;
	// END critical section


	// BEGIN critical section
		std::shared_ptr<const ControlSignal> pControl_signal;
		mutable std::mutex pControl_signal_mutex;
	// END critical section

	std::atomic_bool should_run;

	// =============================== FastRTPS ================================
	std::shared_ptr<eprosima::fastrtps::Participant> pParticipant;
	std::shared_ptr<eprosima::fastrtps::Subscriber> pSubscriber;
	class SubListener : public eprosima::fastrtps::SubscriberListener
	{
	public:
		// SubListener(const Controller * const);
		SubListener(std::shared_ptr<const Controller>);
		~SubListener() = default;
		void onNewDataMessage(eprosima::fastrtps::Subscriber*) override;
	private:
		const std::shared_ptr<const Controller> pOwner;
		eprosima::fastrtps::SampleInfo_t info;
	} listener;
	// HelloWorldMsgPubSubType rtps_type;
	HelloWorldPubSubType rtps_type;
};

#endif /* end of include guard: CONTROLLER_HPP_RSFU8GQS */
