#ifndef ROS2_INTERFACE_VISUALIZATION_MSGS_MSG_MARKER_IDL_
#define ROS2_INTERFACE_VISUALIZATION_MSGS_MSG_MARKER_IDL_

#include "Duration.idl"
#include "Pose.idl"
#include "Vector3.idl"
#include "CompressedImage.idl"
#include "ColorRGBA.idl"
#include "MeshFile.idl"
#include "UVCoordinate.idl"

module visualization_msgs {
  module msg {
    const long ARROW = 0;
    const long CUBE = 1;
    const long SPHERE = 2;
    const long CYLINDER = 3;
    const long LINE_STRIP = 4;
    const long LINE_LIST = 5;
    const long CUBE_LIST = 6;
    const long SPHERE_LIST = 7;
    const long POINTS = 8;
    const long TEXT_VIEW_FACING = 9;
    const long MESH_RESOURCE = 10;
    const long TRIANGLE_LIST = 11;
    const long ARROW_STRIP = 12;
    const long ADD = 0;
    const long MODIFY = 0;
    const long DELETE = 2;
    const long DELETEALL = 3;

    struct Marker {
      std_msgs::msg::Header header;
      string ns;
      int32 id;
      int32 type;
      int32 action;
      geometry_msgs::msg::Pose pose;
      geometry_msgs::msg::Vector3 scale;
      std_msgs::msg::ColorRGBA color;
      builtin_interfaces::msg::Duration lifetime;
      boolean frame_locked;
      sequence<geometry_msgs::msg::Point> points;
      sequence<std_msgs::msg::ColorRGBA> colors;
      string texture_resource;
      sensor_msgs::msg::CompressedImage texture;
      sequence<visualization_msgs::msg::UVCoordinate> uv_coordinates;
      string text;
      string mesh_resource;
      visualization_msgs::msg::MeshFile mesh_file;
      boolean mesh_use_embedded_materials;
    };
  };
};

#endif // ROS2_INTERFACE_VISUALIZATION_MSGS_MSG_MARKER_IDL_
