#ifndef ROS2_INTERFACE_DLS2_INTERFACES_MSG_TEST_IDL_
#define ROS2_INTERFACE_DLS2_INTERFACES_MSG_TEST_IDL_

module dls2_interfaces {
  module msg {
    struct Test{
        double num;
    };
  };
};

#endif // ROS2_INTERFACE_DLS2_INTERFACES_MSG_TEST_IDL_
