<package format="2">
  <name>hyq_commons2</name>
  <version>1.0.0</version>
  <description>
        hyq-commons.
  </description>
  <maintainer email="gennaro.raiola@iit.it">Gennaro Raiola</maintainer>
  <license>BSD</license>

  <buildtool_depend>catkin</buildtool_depend>

  <depend>iit_commons2</depend>

  <test_depend>rostest</test_depend>

</package>
