/*******************************************************************************
*                                                       ,----,                 *
*                                                     .'   .' \                *
*                                                   ,----,'    |               *
*               ________  ___       ________        |    :  .  ;               *
*              |\   ___ \|\  \     |\   ____\       ;    |.'  /                *
*              \ \  \_|\ \ \  \    \ \  \___|_      `----'/  ;                 *
*               \ \  \ \\ \ \  \    \ \_____  \       /  ;  /                  *
*                \ \  \_\\ \ \  \____\|____|\  \     ;  /  /-,                 *
*                 \ \_______\ \_______\____\_\  \   /  /  /.`|                 *
*                  \|_______|\|_______|\_________\./__;      :                 *
*                                     \|_________||   :    .'                  *
*                                                 ;   | .'                     *
*                                                 `---'                        *
*******************************************************************************/
struct HpuMsg
{
  double pressure;
  double status_word;
  double vesc1_status;
  double vesc2_status;
  double vesc1_sw_ver;
  double vesc2_sw_ver;
  double temp_expansion_board;
  double vesc1_board_temp;
  double vesc2_board_temp;
  double vesc1_mot_temp;
  double vesc2_mot_temp;
  double temp1;
  double temp2;
  double temp3;
  double vesc1_act_cur;
  double vesc2_act_cur;
  double vesc1_act_spd;
  double vesc2_act_spd;
  double reserved;
  double vesc1_fb_duty_cycle;
  double vesc2_fb_duty_cycle;
  double vesc1_demand;
  double vesc2_demand;
  double pwm1_duty_cycle;
  double pwm2_duty_cycle;
};
