/*******************************************************************************
*                                                       ,----,                 *
*                                                     .'   .' \                *
*                                                   ,----,'    |               *
*               ________  ___       ________        |    :  .  ;               *
*              |\   ___ \|\  \     |\   ____\       ;    |.'  /                *
*              \ \  \_|\ \ \  \    \ \  \___|_      `----'/  ;                 *
*               \ \  \ \\ \ \  \    \ \_____  \       /  ;  /                  *
*                \ \  \_\\ \ \  \____\|____|\  \     ;  /  /-,                 *
*                 \ \_______\ \_______\____\_\  \   /  /  /.`|                 *
*                  \|_______|\|_______|\_________\./__;      :                 *
*                                     \|_________||   :    .'                  *
*                                                 ;   | .'                     *
*                                                 `---'                        *
*******************************************************************************/
#include "header.idl"
#include "imu_kvh.idl"
#include "imu_mgx.idl"

struct HyQRawMsg
{
	HeaderMsg header;
	ImuKvhMsg imu_kvh;
	ImuMgxMsg imu_mgx;
	unsigned long abs_enc[12]; // 0-4096 (counts)
	unsigned long rel_enc[12]; // 0-80000 (counts)
	unsigned short torque_sensor_haa[4]; // 0-2^16-1 = 0-4V
	unsigned short load_cell_hfe[4]; // 0-2^16-1 = 0-4V
	unsigned short load_cell_kfe[4]; // 0-2^16-1 = 0-4V
};
