/*******************************************************************************
*                                                       ,----,                 *
*                                                     .'   .' \                *
*                                                   ,----,'    |               *
*               ________  ___       ________        |    :  .  ;               *
*              |\   ___ \|\  \     |\   ____\       ;    |.'  /                *
*              \ \  \_|\ \ \  \    \ \  \___|_      `----'/  ;                 *
*               \ \  \ \\ \ \  \    \ \_____  \       /  ;  /                  *
*                \ \  \_\\ \ \  \____\|____|\  \     ;  /  /-,                 *
*                 \ \_______\ \_______\____\_\  \   /  /  /.`|                 *
*                  \|_______|\|_______|\_________\./__;      :                 *
*                                     \|_________||   :    .'                  *
*                                                 ;   | .'                     *
*                                                 `---'                        *
********************************************************************************
* Author:            Hendrik de Bruin                                          *
* Maintainer:        Hendrik de Bruin                                          *
* author email:      hendrik.debruin@iit.it                                    *
*******************************************************************************/
#ifndef GAIT_GENERATOR_HPP_5MDX0BG2
#define GAIT_GENERATOR_HPP_5MDX0BG2
// =============================================================================
// Includes
// =============================================================================
#include "dls2/application_framework/components/periodic_app_layer_component.hpp"
#include "dls2/gait_generator/gait_signal.hpp"
#include "dls2/robot/robot.hpp"

#include <mutex>
#include <memory>
#include <atomic>

#include "dls2/util/messaging/publisher_base.hpp"
#include "dls2/msg/gait_signalPubSubTypes.h"

// =============================================================================
// Class Interface
// =============================================================================
namespace dls
{
class GaitGenerator : public PeriodicAppLayerComponent
{
protected:
	// TODO this is repeated in Controller. Refactor this into one location
	typedef std::chrono::duration<double, std::ratio<1, 1'000'000>> period_t;

public:
	// Typedefs
	// using ID_t = std::string;
	typedef GaitGenerator *create_t();
	typedef void destroy_t(GaitGenerator*);

	// Constructors
	GaitGenerator
	(
		const std::shared_ptr<Dog>&,	///< A pointer to the robot model
		const ID_t&,					///< The ID of the gait generator
		const period_t&					///< The period of the gait generator
	);

	virtual ~GaitGenerator() = default;
	///// Returns the ID of this gait generator
	/////
	///// @ret the ID
	//ID_t getID();

protected:
	void publishData(const GaitSignal &);

	// TODO remove this overload
	/// sends the signal of this generator to the rest of the architecture
	///
	/// @param pData a pointer to the value of the signal at the end of the
	/// current epoch
	void publishData(const std::shared_ptr<GaitSignal> &pData);

	const std::shared_ptr<const Dog> pRobot;	///< A pointer to the robot model
	// const ID_t ID;								///< The ID of this gait generator

private:
	// BEGIN critical section
		/// Signal generated by this gait generator
		///
		/// This member gets overwritten during the call to publishData. It can
		/// be read using readSignal. It is done this way so that anyone reading
		/// the signal from this generator will get a coherent view of the
		/// signal at the end of an epoch. Fields in the signal will not be from
		/// different epochs
		std::shared_ptr<GaitSignal> pData;
		std::mutex data_mutex;
	// END critical section

	PublisherBase<GaitSignalMsgPubSubType> publisher;
};
} // end namespace dls

#endif /* end of include guard: GAIT_GENERATOR_HPP_5MDX0BG2 */
