add_subdirectory(message_wrappers)
# add_subdirectory(gait_generator)
# add_subdirectory(core_framework)
# add_subdirectory(child_process)
# add_subdirectory(class_loader)
# add_subdirectory(topic_info)
# add_subdirectory(estimator)
# add_subdirectory(controller)
# add_subdirectory(log_trace)
add_subdirectory(geometry)
# add_subdirectory(command)
add_subdirectory(pubsub)
# add_subdirectory(main)
