add_subdirectory(message_wrappers)
add_subdirectory(simulators)
add_subdirectory(motion_generator)
add_subdirectory(core_framework)
add_subdirectory(child_process)
add_subdirectory(class_loader)
add_subdirectory(controller)
add_subdirectory(hardware)
add_subdirectory(domains)
add_subdirectory(component)
add_subdirectory(estimator)
add_subdirectory(command)
add_subdirectory(service)
add_subdirectory(ddscom)
add_subdirectory(topics)
add_subdirectory(time)
add_subdirectory(math)
add_subdirectory(main)
add_subdirectory(log)
add_subdirectory(foxglove)
add_subdirectory(profile)