# use RPATH for the build tree
set(CMAKE_SKIP_BUILD_RPATH FALSE)

# the install RPATH is not used when building
set(CMAKE_BUILD_WITH_INSTALL_RPATH FALSE)

# add to RPATH automatically determined paths for the install tree
set(CMAKE_INSTALL_RPATH_USE_LINK_PATH TRUE)

add_subdirectory(message_wrappers)
add_subdirectory(motion_generator)
add_subdirectory(ddscom)
add_subdirectory(application)
add_subdirectory(parameter_server)
add_subdirectory(web_socket_translator)
add_subdirectory(core_framework)
add_subdirectory(child_process)
add_subdirectory(class_loader)
add_subdirectory(controller)
add_subdirectory(hardware)
add_subdirectory(domains)
add_subdirectory(estimator)
add_subdirectory(command)
add_subdirectory(supervisor)
add_subdirectory(service)
add_subdirectory(topics)
add_subdirectory(time)
add_subdirectory(math)
add_subdirectory(main)
add_subdirectory(log)
add_subdirectory(mcap)
add_subdirectory(profile)
add_subdirectory(plugin)
add_subdirectory(action)
add_subdirectory(state_machine)
add_subdirectory(action_client_stock)
add_subdirectory(utils)
add_subdirectory(procedures)
