# ==============================================================================
# Environment setup
# ==============================================================================
image: server-harbor:80/dls2/dls2-env:latest

before_script:
  - source /root/dls_gitlab_ci/gitlab-script.sh

# ==============================================================================
# Stages
# ==============================================================================
stages:
  - build
  - test
  - deploy

# ------------------------------------------------------------------------------
# Build Stage
# ------------------------------------------------------------------------------
# Print versions of installed programmes on the docker image. This is helpful
# for a quick sanity check when things break
display:versions:
  stage: build
  tags:
    - dls2
  script:
    - cmake --version
    - gcc --version
    - g++ --version

# Build the framework
build:dls2:
  stage: build
  tags:
    - dls2
  script:
    - git submodule update --init --recursive
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release ..
    - echo nproc=$(nproc)
    - make -j$(nproc)
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(readlink -f ../bin)
    - echo $LD_LIBRARY_PATH
    - make -j$(nproc)
  artifacts:
    paths:
      - build/*
      - bin/*
    expire_in: 3 hrs

# ------------------------------------------------------------------------------
# Test Stage
# ------------------------------------------------------------------------------
# Run the test cases that have been developed for the framework
test:dls2:
  stage: test
  dependencies:
    - build:dls2
  tags:
    - dls2
  script:
    - cd build
    - make -j$(nproc) tests
    - make test
  only:
    - master
    - devel

# ------------------------------------------------------------------------------
# Deploy Stage
# ------------------------------------------------------------------------------
deploy:dls2:
  stage: deploy
  tags:
    - dls2
  script:
    # build the debians set up by cmake
    - cd build
    - make package
    - cd ..
    # sync to server
    - source /root/dls_gitlab_ci/make-json.bash token=$DLSUSER_TOKEN project=$CI_PROJECT_ID branch=$CI_COMMIT_BRANCH job=$CI_JOB_ID tag=latest > out.json
    - 'curl -X post -H "Content-Type: application/json" -d @out.json http://server-ubuntu18:9000/hooks/deploy-apt'
  artifacts:
    paths:
      - build/*.deb
    expire_in: 1 week
  dependencies:
    - build:dls2
  only:
    - master
    
###################################################################################################
#
# EXPERIMENTAL
#
###################################################################################################
    
display-versions:
  stage: build
  image: server-harbor:80/dls2/dls2-env:$RELEASE
    - dls2
  script:
    - cmake --version
    - gcc --version
    - g++ --version
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /\[exp\]/ && $CI_COMMIT_BRANCH == "master" && $RELEASE == "xenial"'
    - if: '$CI_COMMIT_MESSAGE =~ /\[exp\]/ && $CI_COMMIT_BRANCH == "master" && $RELEASE == "bionic"'
    - if: '$CI_COMMIT_MESSAGE =~ /\[exp\]/ && $CI_COMMIT_BRANCH == "master" && $RELEASE == "focal"'    
