# ==============================================================================
# Environment setup
# ==============================================================================
image: server-gitlab-runner:5000/dls2-framework-dev:latest

before_script:
  - source /root/dls_gitlab_ci/gitlab-script.sh
  - source /opt/ros/kinetic/setup.bash

# ==============================================================================
# Stages
# ==============================================================================
stages:
  - build
  - test
  - deploy

# ------------------------------------------------------------------------------
# Build Stage
# ------------------------------------------------------------------------------
# Print versions of installed programmes on the docker image. This is helpful
# for a quick sanity check when things break
display:versions:
  stage: build
  tags:
    - dls2
  script:
    - cmake --version

# Build the framework
build:dls2:
  stage: build
  tags:
    - dls2
  script:
    - git submodule update --init --recursive
    - mkdir build
    - cd build
    - cmake ..
    - make -j$(nproc)
  artifacts:
    paths:
      - build/*
      - bin/*
    expire_in: 3 hrs

# ------------------------------------------------------------------------------
# Test Stage
# ------------------------------------------------------------------------------
# Run the test cases that have been developed for the framework
test:dls2:
  stage: test
  dependencies:
    - build:dls2
  tags:
    - dls2
  script:
    - cd build
    - make -j$(nproc) tests
    - make test
  only:
    - master
    - devel

# Build the example projects. If these projects do not compile, then something
# has changed in the API of the project. Since the documentation is built from
# these example projects, this would mean that the documentation that ships with
# the framework is now out of date. In such cases you should either rever the
# API changes, or fix the example projects to reflect the new API. That way
# users will always have the latest documenatation on their machines,
test:docs:
  stage: test
  dependencies:
    - build:dls2
  tags:
    - dls2
  script:
    - cd build
    - make install
    - cd ..
    - "[ -d doc/dls2_examples/build ] || mkdir doc/dls2_examples/build"
    - cd doc/dls2_examples/build
    - cmake ..
    - make -j$(nproc)
  only:
    - master
    - devel

# ------------------------------------------------------------------------------
# Deploy Stage
# ------------------------------------------------------------------------------
deploy:dls2:
  stage: deploy
  tags:
    - dls2
  script:
    # build the debians set up by cmake
    - cd build
    - make package
    - cd ..

    # put the catkin_ws into a debian
    - cd catkin_ws
    - catkin_make install
    - mkdir --parents packaging/dls2_ws/opt/dls2/dls2_ws
    - cp -r install/* packaging/dls2_ws/opt/dls2/dls2_ws
    - cd packaging
    - chmod -R 755 dls2_ws
    - dpkg-deb --build dls2_ws
    - cd ../..
    - mv catkin_ws/packaging/dls2_ws.deb build/dls2_ws.deb

    # sync to server
    - source /root/dls_gitlab_ci/make-json.bash $DLSUSER_TOKEN $CI_PROJECT_ID $CI_COMMIT_BRANCH $CI_JOB_ID > out.json
    - 'curl -X post -H "Content-Type: application/json" -d @out.json http://server-ubuntu18:9000/hooks/deploy-apt'
  artifacts:
    paths:
      - build/*.deb
    expire_in: 1 week
  dependencies:
    - build:dls2
  only:
    - master
