set(GRAPHVIZ_EXTERNAL_LIBS  TRUE)
set(GRAPHVIZ_UNKNOWN_LIBS   TRUE)
set(GRAPHVIZ_CUSTOM_TARGETS TRUE)

list(APPEND GRAPHVIZ_IGNORE_TARGETS
	launch_framework_from_src_tree
	compile_test

	# catkin_ws noise - generated by setting "GRAPHVIZ_CUSTOM_TARGETS" to TRUE
	roscpp_generate_messages_cpp
	roscpp_generate_messages_eus
	roscpp_generate_messages_lisp
	roscpp_generate_messages_nodejs
	roscpp_generate_messages_py
	rosgraph_msgs_generate_messages_cpp
	rosgraph_msgs_generate_messages_eus
	rosgraph_msgs_generate_messages_lisp
	rosgraph_msgs_generate_messages_nodejs
	rosgraph_msgs_generate_messages_py
	std_msgs_generate_messages_cpp
	std_msgs_generate_messages_eu
	std_msgs_generate_messages_lisp
	std_msgs_generate_messages_nodejs
	std_msgs_generate_messages_py

	/opt/ros/kinetic
	/usr/lib

	^dl$
	pthread
	readline
)
