set(GRAPHVIZ_EXTERNAL_LIBS  TRUE)
set(GRAPHVIZ_UNKNOWN_LIBS   TRUE)
set(GRAPHVIZ_CUSTOM_TARGETS TRUE)

list(APPEND GRAPHVIZ_IGNORE_TARGETS
	launch_framework_from_src_tree
	compile_test

	# catkin_ws noise - generated by setting "GRAPHVIZ_CUSTOM_TARGETS" to TRUE
	^roscpp
	^rosgraph
	^std_msgs

	/opt/ros/kinetic
	/usr/lib

	^dl$
	^test
	readline
)
