
struct LegsPoseMsg
{
	// Header
	string frame_id;
	unsigned long sequence_id;
	double timestamp;

	double linear_velocity[12];
	double angular_velocity[12];

	double base_velocity[3];

	double stance_status[4];
};
