// Message for aliengo
struct TrunkControllerDebugMsg
{
	// Header
	string frame_id;
	unsigned long sequence_id;
	double timestamp;

	// Actual feet forces
	double feet_forces[12];
	double desired_forces[12];
	double desired_wrench[6];

	double friction_coefficients[4];

	double gravity_term[12];
	double coriolis_centrifugal_terms[12];
};
