hyq:
  dls2_to_roscontrol:
    type: dls2_to_roscontrol/Dls2ToRoscontrol
    publish_rate: 250
    joints:
      - lf_haa_joint
      - lf_hfe_joint
      - lf_kfe_joint
      - rf_haa_joint
      - rf_hfe_joint
      - rf_kfe_joint
      - lh_haa_joint
      - lh_hfe_joint
      - lh_kfe_joint
      - rh_haa_joint
      - rh_hfe_joint
      - rh_kfe_joint
    gains:
      lf_haa_joint: {p: 300.0, i: 0.0, d: 10.0}
      lf_hfe_joint: {p: 300.0, i: 0.0, d: 10.0}
      lf_kfe_joint: {p: 200.0, i: 0.0, d: 6.0}
      rf_haa_joint: {p: 300.0, i: 0.0, d: 10.0}
      rf_hfe_joint: {p: 300.0, i: 0.0, d: 10.0}
      rf_kfe_joint: {p: 200.0, i: 0.0, d: 6.0}
      lh_haa_joint: {p: 300.0, i: 0.0, d: 10.0}
      lh_hfe_joint: {p: 300.0, i: 0.0, d: 10.0}
      lh_kfe_joint: {p: 200.0, i: 0.0, d: 6.0}
      rh_haa_joint: {p: 300.0, i: 0.0, d: 10.0}
      rh_hfe_joint: {p: 300.0, i: 0.0, d: 10.0}
      rh_kfe_joint: {p: 200.0, i: 0.0, d: 6.0}
#      ptu_pan: {p: 100, i: 0.0, d: 10.0}
#      ptu_tilt: {p: 100, i: 0.0, d: 10.0}
    end_effectors:
      - lf
      - rf
      - lh
      - rh

