
#ifndef GAIT_SIGNAL_HPP
#define GAIT_SIGNAL_HPP

#include "dls2/msg_wrappers/wrapper.hpp"
#include "dls_messages/dds/gait_signal.h"
#include "dls2/msg_wrappers/pose.hpp"
#include "dls2/msg_wrappers/screw.hpp"
#include <robotlib/robot_base.hpp>

/// A structure containing the data streams that make up the signal at the
/// current time generated by a given gait generator
namespace dls
{
	struct GaitSignal : public Wrapper<GaitSignalMsg>
	{
		GaitSignal(const std::shared_ptr<robotlib::RobotBase> robot);
		GaitSignal(GaitSignal& gait_signal);
		GaitSignal() = delete;
		virtual ~GaitSignal();
		
		operator GaitSignalMsg() const override;
		GaitSignal& operator= (const GaitSignalMsg& gait_signal_msg) override;
		GaitSignal& operator=(const GaitSignal& gait_signal);

		std::string frame_id_{};
		uint32_t sequence_id_{};
		double timestamp_{};

		Pose desired_com_pose_world_;            ///< The desired pose of the center of mass frame
		Screw desired_com_velocity_world_;        ///< The desired velocity of the center of mass frame
		Screw desired_com_acceleration_world_;    ///< The desired accleration of the center of mass frame

		/// Desired joint position, velocity and acceleration.
		/// The effort field corresponds to the desired feed-forward torques
		robotlib::JointState desired_joints_position_;
		robotlib::JointState desired_joints_velocity_;
		robotlib::JointState desired_joints_acceleration_;
		robotlib::JointState desired_joints_effort_;

		robotlib::LegDataMap<bool> stance_legs_;
	};
} // namespace dls
#endif