/*******************************************************************************
*                                                       ,----,                 *
*                                                     .'   .' \                *
*                                                   ,----,'    |               *
*               ________  ___       ________        |    :  .  ;               *
*              |\   ___ \|\  \     |\   ____\       ;    |.'  /                *
*              \ \  \_|\ \ \  \    \ \  \___|_      `----'/  ;                 *
*               \ \  \ \\ \ \  \    \ \_____  \       /  ;  /                  *
*                \ \  \_\\ \ \  \____\|____|\  \     ;  /  /-,                 *
*                 \ \_______\ \_______\____\_\  \   /  /  /.`|                 *
*                  \|_______|\|_______|\_________\./__;      :                 *
*                                     \|_________||   :    .'                  *
*                                                 ;   | .'                     *
*                                                 `---'                        *
*******************************************************************************/
#ifndef GAIT_SIGNAL_HPP_DLF4YRRS
#define GAIT_SIGNAL_HPP_DLF4YRRS

#include "dls2/msg_wrappers/wrapper.hpp"
#include "dls_messages/dds/gait_signal.h"
#include "dls2/msg_wrappers/screw.hpp"
#include "dls2/msg_wrappers/pose.hpp"

#include <robotlib/robot_base.hpp>

/// A structure containing the data streams that make up the signal at the
/// current time generated by a given gait generator
namespace dls
{
	struct GaitSignal : public Wrapper<GaitSignalMsg>
	{
		GaitSignal(const std::shared_ptr<robotlib::RobotBase>);
		GaitSignal(GaitSignal&);
		GaitSignal() = delete;
		virtual ~GaitSignal() = default;
		// GaitSignal(const std::shared_ptr<robotlib::RobotBase>&, GaitSignalMsg);
		
		operator GaitSignalMsg() const override;
		GaitSignal& operator= (GaitSignalMsg&) override;

		Pose desired_com_pose_world;            ///< The desired pose of the center of mass frame
		Screw desired_com_velocity_world;        ///< The desired velocity of the center of mass frame
		Screw desired_com_acceleration_world;    ///< The desired accleration of the center of mass frame

		// Pose desired_base_pose_world;            ///< The desired pose of the base frame
		// Screw desired_base_velocity_world;        ///< The desired velocity of the base frame
		// Screw desired_base_acceleration_world;    ///< The desired acceleration of the base frame

		/// The desired joint state
		///
		/// This object contaisn the desired joint position, velocity and
		/// acceleration. The effort field corresponds to the desired feed-forward
		/// torques
		robotlib::JointState desired_joint_position;
		robotlib::JointState desired_joint_velocity;
		robotlib::JointState desired_joint_acceleration;
		robotlib::JointState desired_joint_effort;
			
		/// Data map of legs that are in contact with the ground
		///
		robotlib::LegDataMap<bool> stance_legs;

		/// Desired wrench on the base
		///
		// Screw desired_base_wrench;
	};
} // end namespace dls
#endif /* end of include guard: GAIT_SIGNAL_HPP_DLF4YRRS */
