/*******************************************************************************
*                                                       ,----,                 *
*                                                     .'   .' \                *
*                                                   ,----,'    |               *
*               ________  ___       ________        |    :  .  ;               *
*              |\   ___ \|\  \     |\   ____\       ;    |.'  /                *
*              \ \  \_|\ \ \  \    \ \  \___|_      `----'/  ;                 *
*               \ \  \ \\ \ \  \    \ \_____  \       /  ;  /                  *
*                \ \  \_\\ \ \  \____\|____|\  \     ;  /  /-,                 *
*                 \ \_______\ \_______\____\_\  \   /  /  /.`|                 *
*                  \|_______|\|_______|\_________\./__;      :                 *
*                                     \|_________||   :    .'                  *
*                                                 ;   | .'                     *
*                                                 `---'                        *
*******************************************************************************/
#ifndef GAIT_GENERATOR_HPP_5MDX0BG2
#define GAIT_GENERATOR_HPP_5MDX0BG2
// =============================================================================
// Includes
// =============================================================================
#include "dls2/components/periodic_app_layer_component.hpp"
#include "dls2/gait_generator/gait_signal.hpp"
#include "dls2/robot/robot.hpp"
#include "dls2/util/messaging/dds_participant.hpp"
#include "dls2/msg_wrappers/blind_state.hpp"

#include <doglib/base/dog.hpp>

#include <mutex>
#include <memory>
#include <atomic>

// =============================================================================
// Class Interface
// =============================================================================
namespace dls
{
class GaitGenerator : public PeriodicAppLayerComponent
{
	protected:
		// TODO this is repeated in Controller. Refactor this into one location
		typedef std::chrono::duration<double, std::ratio<1, 1'000'000>> period_t;

	public:
		// Typedefs
		// using ID_t = std::string;
		typedef GaitGenerator *create_t(std::shared_ptr<dls::dog::Dog>);
		typedef void destroy_t(GaitGenerator*);

		// Constructors
		GaitGenerator
		(
			const ID_t&,																			///< The ID of the gait generator
			const std::shared_ptr<dog::Dog>&,														///< A pointer to the robot model
			const period_t&,																		///< The period of the gait generator
			const dls::topicType& gateTopic = dls::topics::gait_signal,								///< Topic where gate signal will be published
			const dls::topicType& blindStateTopic = dls::topics::low_level_estimation::blind_state  ///< Topic where blind state signal is being published
		);

		virtual ~GaitGenerator() = default;

	protected:
		void publishData(const GaitSignal &);

		// TODO remove this overload
		/// sends the signal of this generator to the rest of the architecture
		///
		/// @param pData a pointer to the value of the signal at the end of the
		/// current epoch
		void publishData(const std::shared_ptr<GaitSignal> &pData);

		const std::shared_ptr<const dog::Dog> pRobot;	///< A pointer to the robot model

		std::shared_ptr<BlindState> readBlindStateSignal() const;
		
	private:
		// BEGIN critical section
			/// Signal generated by this gait generator
			///
			/// This member gets overwritten during the call to publishData. It can
			/// be read using readSignal. It is done this way so that anyone reading
			/// the signal from this generator will get a coherent view of the
			/// signal at the end of an epoch. Fields in the signal will not be from
			/// different epochs
			std::shared_ptr<GaitSignal> pData;
			std::mutex data_mutex;
		// END critical section

		// BEGIN critical section
			std::shared_ptr<BlindState> pBlind_state_signal;
			mutable std::mutex blind_state_signal_mutex;
		// END crital section

		dls::DDSParticipant ddslink;
	};
} // end namespace dls

#define DLS_EXPORT_GAIT_GENERATOR(generator)                               \
extern "C" dls::GaitGenerator *create(std::shared_ptr<dls::dog::Dog> pDog) \
{                                                                          \
	return new generator(pDog);                                            \
}                                                                          \
extern "C" void destroy(dls::GaitGenerator *p)                             \
{                                                                          \
	delete p;                                                              \
}

#endif /* end of include guard: GAIT_GENERATOR_HPP_5MDX0BG2 */
