# ==============================================================================
# Generation of messages
# ==============================================================================
# Generate message files
#
# This command generates a new shared library named
# $dls_messages.  The library is automatically installed to the
# correct location in the filesystem. The header files are also installed as
# required. This allows 3rd party applications to be built such that they may
# use the messages generated by the current project.
# The dls_add_message function can be used also by other libraries to generate custom messages.

# Set wrapper file path. If it is not in the current directory (e.g. other libraries are trying to use generate messages), the installed path is set
set (WRAPPER_FILE ${CMAKE_CURRENT_LIST_DIR}/wrapper.stg)
if(NOT EXISTS "${WRAPPER_FILE}")
	set (WRAPPER_FILE "/usr/include/dls_messages/cmake/wrapper.stg")
endif()

function(dls_add_message msg library_name)
	set(MESSAGE_DIR "${CMAKE_CURRENT_BINARY_DIR}/include/dls_messages/dds")

	# If I'm generating a message that contains only annotations, the ${msg}PubSubTypes.cxx is not generated, so it is not added to the library
	set (extra_args ${ARGN})
	list(LENGTH extra_args extra_count)
    if (${extra_count} GREATER 0)
        list(GET extra_args 0 optional_arg)
		if(optional_arg STREQUAL "annotation_only")
			set(generated_source
				"${MESSAGE_DIR}/${msg}TypeObjectSupport.cxx"
			)
		endif()
	else()
			set(generated_source
				"${MESSAGE_DIR}/${msg}PubSubTypes.cxx"
				"${MESSAGE_DIR}/${msg}TypeObjectSupport.cxx"
	)
    endif ()

	set(generated_headers
		"${MESSAGE_DIR}/${msg}.hpp"
		"${MESSAGE_DIR}/${msg}PubSubTypes.hpp"
		"${MESSAGE_DIR}/${msg}TypeObjectSupport.hpp"
	)

	# use fastddsgen to generate the message source and header files
	add_custom_command(
		OUTPUT
			${generated_source}
			${generated_headers}
		COMMAND
			[ -d ${MESSAGE_DIR} ] || mkdir --parents ${MESSAGE_DIR}
		COMMAND
			fastddsgen -typeros2 -replace -cs ${CMAKE_CURRENT_SOURCE_DIR}/idls/${msg}.idl -d ${MESSAGE_DIR}
		COMMENT
			"Generating message files for ${msg}.idl"
		DEPENDS
		${CMAKE_CURRENT_SOURCE_DIR}/idls/${msg}.idl
	)

	# add the generated source files to the library
	target_sources(${library_name}
		PRIVATE
		${generated_source}
	)
	
	target_include_directories(${library_name}
	PUBLIC
		${CMAKE_CURRENT_BINARY_DIR}/include
	)

	install(
		FILES 
			${generated_headers}
		DESTINATION 
			/usr/include/dls_messages/dds
		COMPONENT 
			${PROJECT_NAME}_dev
	)
endfunction()