/*******************************************************************************
*                                                       ,----,                 *
*                                                     .'   .' \                *
*                                                   ,----,'    |               *
*               ________  ___       ________        |    :  .  ;               *
*              |\   ___ \|\  \     |\   ____\       ;    |.'  /                *
*              \ \  \_|\ \ \  \    \ \  \___|_      `----'/  ;                 *
*               \ \  \ \\ \ \  \    \ \_____  \       /  ;  /                  *
*                \ \  \_\\ \ \  \____\|____|\  \     ;  /  /-,                 *
*                 \ \_______\ \_______\____\_\  \   /  /  /.`|                 *
*                  \|_______|\|_______|\_________\./__;      :                 *
*                                     \|_________||   :    .'                  *
*                                                 ;   | .'                     *
*                                                 `---'                        *
*******************************************************************************/
#ifndef MOTION_GENERATOR_HPP_5MDX0BG2
#define MOTION_GENERATOR_HPP_5MDX0BG2
// =============================================================================
// Includes
// =============================================================================
#include "dls2/components/periodic_app_layer_component.hpp"
#include "dls2/util/messaging/dds_participant.hpp"
#include "dls2/msg_wrappers/blind_state.hpp"
#include "dls2/msg_wrappers/gait_signal.hpp"

#include "robotlib/robot_factory.hpp"

#include <mutex>
#include <memory>
#include <atomic>

// =============================================================================
// Class Interface
// =============================================================================
namespace dls
{
class MotionGenerator : public PeriodicAppLayerComponent
{
	protected:
		// TODO this is repeated in Controller. Refactor this into one location
		typedef std::chrono::duration<double, std::ratio<1, 1'000'000>> period_t;

	public:
		// Typedefs
		// using ID_t = std::string;
		typedef MotionGenerator *create_t(std::string);
		typedef void destroy_t(MotionGenerator*);

		// Constructors
		MotionGenerator
		(
			const std::string&,																			///< The ID of the motion generator
			const std::shared_ptr<robotlib::RobotBase>&,														///< A pointer to the robot model
			const period_t&,																		///< The period of the motion generator
			const dls::topicType& gateTopic = dls::topics::gait_signal,								///< Topic where gate signal will be published
			const dls::topicType& blindStateTopic = dls::topics::low_level_estimation::blind_state  ///< Topic where blind state signal is being published
		);

		virtual ~MotionGenerator() = default;

	protected:
		void publishData(const GaitSignal &);

		// TODO remove this overload
		/// sends the signal of this generator to the rest of the architecture
		///
		/// @param pData a pointer to the value of the signal at the end of the
		/// current epoch
		void publishData(const std::shared_ptr<GaitSignal> &pData);

		const std::shared_ptr<const robotlib::RobotBase> pRobot;	///< A pointer to the robot model

		BlindState readBlindStateSignal();

        bool readBeat();
		
	private:
		// BEGIN critical section
			/// Signal generated by this motion generator
			///
			/// This member gets overwritten during the call to publishData. It can
			/// be read using readSignal. It is done this way so that anyone reading
			/// the signal from this generator will get a coherent view of the
			/// signal at the end of an epoch. Fields in the signal will not be from
			/// different epochs
			std::shared_ptr<GaitSignal> pData;
			std::mutex data_mutex;
		// END critical section

		// BEGIN critical section
			BlindState blind_state_signal;
			mutable std::mutex blind_state_signal_mutex;
		// END crital section

		void executeCommand(std::string cmd);

        bool heart_beat;

		dls::DDSParticipant ddslink;
		dls::DDSReader 		ddsMonitor;
	};
} // end namespace dls

#endif /* end of include guard: MOTION_GENERATOR_HPP_5MDX0BG2 */