/*******************************************************************************
*                                                       ,----,                 *
*                                                     .'   .' \                *
*                                                   ,----,'    |               *
*               ________  ___       ________        |    :  .  ;               *
*              |\   ___ \|\  \     |\   ____\       ;    |.'  /                *
*              \ \  \_|\ \ \  \    \ \  \___|_      `----'/  ;                 *
*               \ \  \ \\ \ \  \    \ \_____  \       /  ;  /                  *
*                \ \  \_\\ \ \  \____\|____|\  \     ;  /  /-,                 *
*                 \ \_______\ \_______\____\_\  \   /  /  /.`|                 *
*                  \|_______|\|_______|\_________\./__;      :                 *
*                                     \|_________||   :    .'                  *
*                                                 ;   | .'                     *
*                                                 `---'                        *
*******************************************************************************/
#ifndef CONTROLLER_HPP_RSFU8GQS
#define CONTROLLER_HPP_RSFU8GQS

// =============================================================================
// Includes
// =============================================================================
#include "dls2/components/periodic_app_layer_component.hpp"
#include "dls2/gait_generator/gait_signal.hpp"
#include "dls2/controller/controller_data.hpp"
#include "dls2/util/messaging/dds_participant.hpp"
#include "dls2/msg_wrappers/blind_state.hpp"

#include "robotlib/robot_factory.hpp"

#include <chrono>
#include <string>
#include <memory>
#include <atomic>

// =============================================================================
// Class Interface
// =============================================================================
// TODO a lot of functions have been removed from Controller. Many of them need to be put into Dog
namespace dls
{
    class Controller : public PeriodicAppLayerComponent
    {
        friend class ControlLayer;

    public:

        // Plugin typedefs
        typedef Controller *create_t(std::shared_ptr<robotlib::RobotBase>);
        typedef void destroy_t(Controller*);

        Controller
        (
            const std::string&,                                        		 							///< The ID of the controller
            const std::shared_ptr<robotlib::RobotBase>&,                   		 					///< A pointer to the robot model
            const period_t&,                                    		 							///< The period of the controller
            const ControlSignal::SignalReconstructionMethod&,  			 							///< Signal reconstruction used by this controller
            const dls::topicType& controlSignalTopic_ = dls::topics::control_signal,    			///< Topic where control signal should be published
            const dls::topicType& gateTopic_ = dls::topics::gait_signal,	 						///< Topic where gate signal is being published
            const dls::topicType& blindStateTopic_ = dls::topics::low_level_estimation::blind_state ///< Topic where blind state signal is being published
        );

        virtual ~Controller() = default;

        /// Returns the name of the topic where this controller is publishing its
        /// control signal
        std::string getControlSignalTopic() const;

    protected:
        ///// Function gets called each epoch.
        /////
        ///// @param time The time when this function is called,
        //virtual void run(const std::chrono::system_clock::time_point &time) = 0;

        /// Gets the current value of the signal generated by the active gait
        /// generator
        GaitSignal readGaitSignal();

        BlindState readBlindStateSignal();

        /// Sends the control command to the rest of the architecture
        ///
        void publishSignal(const ControlSignal&);

        const std::shared_ptr<const robotlib::RobotBase> pRobot;

        const ControlSignal::SignalReconstructionMethod signal_reconstruction_method;

    private:
        // BEGIN critical section
            /// The last reading of the signal from the current active gait generator
            GaitSignal gait_signal;
            mutable std::mutex gait_signal_mutex;
        // END critical section


        // BEGIN critical section
            std::shared_ptr<const ControlSignal> pControl_signal;
            mutable std::mutex control_signal_mutex;
        // END critical section

        // BEGIN critical section
            BlindState blind_state_signal;
            mutable std::mutex blind_state_signal_mutex;
        // END crital section

        std::atomic_bool should_run;

        dls::topicType control_signal_topic;
        dls::topicType gait_topic;
        dls::topicType blind_state_topic;

        dls::DDSParticipant ddslink;
        dls::DDSReader  	ddsMonitor;

        void executeCommand(std::string cmd);
};
} // end namespace dls

#endif /* end of include guard: CONTROLLER_HPP_RSFU8GQS */