/*******************************************************************************
*                                                       ,----,                 *
*                                                     .'   .' \                *
*                                                   ,----,'    |               *
*               ________  ___       ________        |    :  .  ;               *
*              |\   ___ \|\  \     |\   ____\       ;    |.'  /                *
*              \ \  \_|\ \ \  \    \ \  \___|_      `----'/  ;                 *
*               \ \  \ \\ \ \  \    \ \_____  \       /  ;  /                  *
*                \ \  \_\\ \ \  \____\|____|\  \     ;  /  /-,                 *
*                 \ \_______\ \_______\____\_\  \   /  /  /.`|                 *
*                  \|_______|\|_______|\_________\./__;      :                 *
*                                     \|_________||   :    .'                  *
*                                                 ;   | .'                     *
*                                                 `---'                        *
*******************************************************************************/
#ifndef GAIT_DATA_HPP_DLF4YRRS
#define GAIT_DATA_HPP_DLF4YRRS

#include "dls2/geometry/pose.hpp"
#include <Eigen/Dense>
#include "dls/messages/gait_signal.h"
#include "dls2/msg_wrappers/screw.hpp"
#include "dls2/msg_wrappers/joint_state.hpp"

#include <iit/commons/dog/leg_bool_map.h>

/// A structure containing the data streams that make up the signal at the
/// current time generated by a given gait generator
// TODO should this class be made thread safe?
// TODO write test code to check the conversions of this class to rtps and back
namespace dls
{
struct GaitSignal
{
	GaitSignal();
	// TODO read up if this should be reference or const or whatever
	GaitSignal(GaitSignalMsg);
	operator GaitSignalMsg() const;

	// TODO can I use Pose class for velocities and accelerations?
	// TODO handle default initialisations here
	Pose desired_com_pose_world;            ///< The desired pose of the center of mass frame
	Screw desired_com_velocity_world;        ///< The desired velocity of the center of mass frame
	Screw desired_com_acceleration_world;    ///< The desired accleration of the center of mass frame

	Pose desired_base_pose_world;            ///< The desired pose of the base frame
	Screw desired_base_velocity_world;        ///< The desired velocity of the base frame
	Screw desired_base_acceleration_world;    ///< The desired acceleration of the base frame

	/// The desired joint state
	///
	/// This object contaisn the desired joint position, velocity and
	/// acceleration. The effort field corresponds to the desired feed-forward
	/// torques
	JointState desired_joint_state;

	/// Data map of legs that are in contact with the ground
	///
	iit::dog::LegBoolMap stance_legs;

	/// Desired wrench on the base
	///
	Screw desired_base_wrench;
};
} // end namespace dls
#endif /* end of include guard: GAIT_DATA_HPP_DLF4YRRS */
