# include(dls_deploy)
# Generate message files
#
# This command generates a new shared library named
# $dls_{PROJECT_NAME}_messaging.  The library is automatically installed to the
# correct location in the filesystem. The header files are also installed as
# required. This allows 3rd party applications to be built such that they may
# use the messages generated by the current project.
#
# To use the messages generated here:
#
# within the same project:
#    1. make the targets that use the messages depend on
#       the target dls_${PROJECT_NAME}_messaging.
#    2. Link them to dls_${PROJECT_NAME}_messaging
#    3. Add to the include path dls_${PROJECT_NAME}_msg_includes
#
# TODO implement this
# from an external project:
#    1. find the package with the find command
#    2. use its includes path
#    3. link to the library
#
# @param msg the name of a message file, without the `.idl` suffix
function(dls_add_message msg)
	# add the messaging library for this project if it has not yet been added
	if(NOT TARGET dls_${PROJECT_NAME}_messaging)
		add_library(dls_${PROJECT_NAME}_messaging SHARED)
		target_compile_options(dls_${PROJECT_NAME}_messaging
			PRIVATE
			-w # Suppress all warnings, this library's code is auto-generated
		)
		# TODO this won't work for third parties using this library since they
		# don't have access to dls_depoy
		dls_install(dls_${PROJECT_NAME}_messaging)
	endif()

	# generate the message files for the given idl file
	set(generated_source
		"${CMAKE_CURRENT_BINARY_DIR}/gen/include/dls2/msg/${msg}.cxx;${CMAKE_CURRENT_BINARY_DIR}/gen/include/dls2/msg/${msg}PubSubTypes.cxx"
	)
	add_custom_command(
		OUTPUT
			# ${CMAKE_CURRENT_BINARY_DIR}/gen/include/dls2/msg/${msg}.cxx
			${CMAKE_CURRENT_BINARY_DIR}/gen/include/dls2/msg/${msg}.h
			# ${CMAKE_CURRENT_BINARY_DIR}/gen/include/dls2/msg/${msg}PubSubTypes.cxx
			${CMAKE_CURRENT_BINARY_DIR}/gen/include/dls2/msg/${msg}PubSubTypes.h
			${generated_source}
		COMMAND
			[ -d ${CMAKE_CURRENT_BINARY_DIR}/gen/include/dls2/msg ] || mkdir --parents ${CMAKE_CURRENT_BINARY_DIR}/gen/include/dls2/msg
		COMMAND
			fastrtpsgen -replace ${CMAKE_CURRENT_SOURCE_DIR}/${msg}.idl -d ${CMAKE_CURRENT_BINARY_DIR}/gen/include/dls2/msg
		COMMENT
			"Generating message files for ${msg}.idl"
		DEPENDS
			${msg}.idl
	)

	target_sources(dls_${PROJECT_NAME}_messaging
		PRIVATE
		${generated_source}
		# ${CMAKE_CURRENT_BINARY_DIR}/gen/include/dls2/msg/${msg}.cxx
		# ${CMAKE_CURRENT_BINARY_DIR}/gen/include/dsl2/msg/${msg}PubSubTypes.cxx
	)
endfunction()

# Define the include path for the messages
if(NOT dls_${PROJECT_NAME}_messaging)
	set(dls_${PROJECT_NAME}_msg_includes
		"${CMAKE_CURRENT_BINARY_DIR}/gen/include/dls2/msg"
		PARENT_SCOPE
	)
endif()
