# Gets the name of a file configured with dls_configure
function(dls_configure_name INFILE OUTFILE)
	# Assert file has '.in' final extension'
	get_filename_component(FINAL_EXTENSION ${INFILE} LAST_EXT)
	if(NOT ${FINAL_EXTENSION} STREQUAL ".in")
		message(FATAL_ERROR
			"Error: ${INFILE} expected to end with extension '.in'"
		)
	endif()
	# Name of the file without the '.in' suffix
	get_filename_component(OUTNAME ${INFILE} NAME_WLE)
	set(${OUTFILE} ${OUTNAME} PARENT_SCOPE)
endfunction()

# Gets the location where a file generated by dls_configure is stored
function(dls_configure_destination INFILE OUTPATH)
	# Name of the file, converting relative path to full path if required
	get_filename_component(RESOLVED_PATH ${INFILE} REALPATH)

	# Path to the file
	get_filename_component(FULLPATH ${RESOLVED_PATH} DIRECTORY)

	# Get the path relative to the root of the project directory
	string(REPLACE ${PROJECT_SOURCE_DIR}/ "" ROOT_RELATIVE_PATH ${FULLPATH})

	# Put the relative directory inside the build location
	set(${OUTPATH}
		${PROJECT_BINARY_DIR}/${ROOT_RELATIVE_PATH}
		PARENT_SCOPE
	)
endfunction()

# Calls configure_file, and automatically puts the file in the correct location
function(dls_configure INFILE OUTNAME)
	message("CONFIGURE1 ${INFILE}")
	dls_configure_name(${INFILE} CONFIGURE_NAME)
	message("CONFIGURe2")
	dls_configure_destination(${INFILE} CONFIGURE_DESTINATION)
	message("CONFIGURE3")
	configure_file(${INFILE} ${CONFIGURE_DESTINATION}/${CONFIGURE_NAME})
	message("cOnFigure4")
	set(${OUTNAME} ${CONFIGURE_DESTINATION}/${CONFIGURE_NAME} PARENT_SCOPE)
	message("ConfigureEND ${INFILE} ${CONFIGURE_DESTINATION}/${CONFIGURE_NAME}")
endfunction()

# Calls configure_file with @ONLY, and automatically puts the file in the
# correct location
function(dls_configure_atonly INFILE OUTNAME)
	message("CONFIGUATONLY1 ${INFILE}")
	dls_configure_name(${INFILE} CONFIGURE_NAME)
	message("CONFIGUATONLY2")
	dls_configure_destination(${INFILE} CONFIGURE_DESTINATION)
	message("CONFIGUATONLY3")
	configure_file(${INFILE} ${CONFIGURE_DESTINATION}/${CONFIGURE_NAME} @ONLY)
	message("CONFIGUATONLY4")
	set(${OUTNAME} ${CONFIGURE_DESTINATION}/${CONFIGURE_NAME} PARENT_SCOPE)
	message("CONFIGUATONLY END ${INFILE} ${CONFIGURE_DESTINATION}/${CONFIGURE_NAME}")
endfunction()
