# The variable DLS_MESSAGE_HEADER_DESTINATION sets where the current project
# should place the generated message header files, as well as where to install
# them. This variable should not be modified by client code. The variable is
# intended to make it possible to give each client the ability to generate
# messages without having to worry about whether they are overwriting other
# third party messages.
#
# This variable is currently set in the following locations:
#
# * When compiling the main framework, it is set in the toplevel CMakeLists.txt
# * When compiling a plugin, it is set inside dls_install.cmake.in
#
# This variable should be treated as a constant
if(NOT DLS_MESSAGE_HEADER_DESTINATION)
	message(FATAL_ERROR
		"The variable 'DLS_MESSAGE_HEADER_DESTINATION' must be set before "
		"including the file 'dls_message.cmake'. "
		"This is an internal variable "
		"to the framework. If you are compiling client code and see this error, "
		"please contact the maintainer. If you are compiling the framework, see "
		"the documentation at the source location of this error message"
	)
endif()
# ==============================================================================
# Configure message installation groups
# ==============================================================================
function(dls_register_message_component_impl)
	if(NOT ${PROJECT_NAME} STREQUAL "dls2")
		string(TOUPPER ${PROJECT_NAME} PROJECT_NAME_UPPER)
		set(CPACK_DEBIAN_DLS2_${PROJECT_NAME_UPPER}_MESSAGING_FILE_NAME
			"dls2-${PROJECT_NAME}-messaging-${PROJECT_VERSION}.deb"
			PARENT_SCOPE
		)
		set(CPACK_DEBIAN_${PROJECT_NAME_UPPER}_MESSAGING_PACKAGE_NAME
			"dls2-${PROJECT_NAME}-messaging.deb"
			PARENT_SCOPE
		)
	else()
		set(CPACK_DEBIAN_DLS2_DLS2_MESSAGING_FILE_NAME
			"dls2-messaging-${PROJECT_VERSION}.deb"
			PARENT_SCOPE
		)
		set(CPACK_DEBIAN_DLS2_DLS2_MESSAGING_PACKAGE_NAME
			"dls2-messaging"
			PARENT_SCOPE
		)
	endif()
endfunction()
dls_register_message_component_impl()

# ==============================================================================
# Generation of messages
# ==============================================================================
# Generate message files
#
# This command generates a new shared library named
# $dls_{PROJECT_NAME}_messaging.  The library is automatically installed to the
# correct location in the filesystem. The header files are also installed as
# required. This allows 3rd party applications to be built such that they may
# use the messages generated by the current project.
#
# To use the messages generated here:
#
# within the same project:
#    1. make the targets that use the messages depend on
#       the target dls_${PROJECT_NAME}_messaging.
#    2. Link them to dls_${PROJECT_NAME}_messaging
#    3. Add to the include path dls_${PROJECT_NAME}_msg_includes
#
# TODO implement this
# from an external project:
#    1. find the package with the find command
#    2. use its includes path
#    3. link to the library
#
# @param msg the name of a message file, without the `.idl` suffix
function(dls_add_message msg)
	# On the first call of this function, do the following:
	#
	# * create the messaging library for this project
	# * set its compile options to supress warnings
	# * mark it for installation using as part of the proper group
	if(NOT TARGET dls_${PROJECT_NAME}_messaging)
		add_library(dls_${PROJECT_NAME}_messaging SHARED)
		target_compile_options(dls_${PROJECT_NAME}_messaging
			PRIVATE
			-w # Suppress all warnings, this library's code is auto-generated
		)
		target_include_directories(dls_${PROJECT_NAME}_messaging
			PUBLIC
			${CMAKE_CURRENT_BINARY_DIR}/gen/include
		)
		install(
			TARGETS dls_${PROJECT_NAME}_messaging
			LIBRARY
				DESTINATION ${DLS_INSTALL_MESSAGES_DIR}
				COMPONENT dls2_${PROJECT_NAME}_messaging
		)
		target_include_directories(dls_${PROJECT_NAME}_messaging
			PUBLIC
			${CMAKE_CURRENT_BINARY_DIR}/gen/include
		)
	endif()

	set(generated_source
		"${CMAKE_CURRENT_BINARY_DIR}/gen/include/${DLS_MESSAGE_HEADER_DESTINATION}/${msg}.cxx;${CMAKE_CURRENT_BINARY_DIR}/gen/include/${DLS_MESSAGE_HEADER_DESTINATION}/${msg}PubSubTypes.cxx"
	)
	set(generated_headers
		"${CMAKE_CURRENT_BINARY_DIR}/gen/include/${DLS_MESSAGE_HEADER_DESTINATION}/${msg}.h;${CMAKE_CURRENT_BINARY_DIR}/gen/include/${DLS_MESSAGE_HEADER_DESTINATION}/${msg}PubSubTypes.h"
	)

	# use fastddsgen to generate the message source and header files
	add_custom_command(
		OUTPUT
			${generated_source}
			${generated_headers}
		COMMAND
			[ -d ${CMAKE_CURRENT_BINARY_DIR}/gen/include/${DLS_MESSAGE_HEADER_DESTINATION} ] || mkdir --parents ${CMAKE_CURRENT_BINARY_DIR}/gen/include/${DLS_MESSAGE_HEADER_DESTINATION}
		COMMAND
			fastddsgen -replace ${CMAKE_CURRENT_SOURCE_DIR}/${msg}.idl -d ${CMAKE_CURRENT_BINARY_DIR}/gen/include/${DLS_MESSAGE_HEADER_DESTINATION}
		COMMAND
			${PROJECT_SOURCE_DIR}/scripts/fix_msg.bash ${CMAKE_CURRENT_BINARY_DIR}/gen/include/${DLS_MESSAGE_HEADER_DESTINATION} ${msg}
		COMMENT
			"Generating message files for ${msg}.idl"
		DEPENDS
			${msg}.idl
	)



	# add the generated source files to the library
	target_sources(dls_${PROJECT_NAME}_messaging
		PRIVATE
		${generated_source}
	)

	install(FILES ${generated_headers}
		DESTINATION include/${DLS_MESSAGE_HEADER_DESTINATION}
		COMPONENT dls2_${PROJECT_NAME}_messaging
	)

	set(dls_${PROJECT_NAME}_msg_includes
		"${CMAKE_CURRENT_BINARY_DIR}/gen/include"
		CACHE STRING "project message dir"
	)
endfunction()
