#ifndef GAIT_GENERATOR_HPP_5MDX0BG2
#define GAIT_GENERATOR_HPP_5MDX0BG2

#include "application_framework/components/app_layer_component.hpp"
#include "gait_generator/gait_signal.hpp"
#include "todo.h"

#include <mutex>
#include <memory>

class Dog;
class GaitGenerator : public AppLayerComponent
{
protected:
	TODO("this is repeated in Controller. Refactor this into one location")
	typedef std::chrono::duration<double, std::ratio<1, 1'000'000>> period_t;

public:
	// Typedefs
	using ID_t = std::string;
	typedef GaitGenerator *create_t();
	typedef void destroy_t(GaitGenerator*);

	// Constructors
	GaitGenerator
	(
		const std::shared_ptr<Dog>&,	///< A pointer to the robot model
		const ID_t&,					///< The ID of the gait generator
		const period_t&					///< The period of the gait generator
	);

	virtual ~GaitGenerator() = default;

	/// Returns the ID of this gait generator
	///
	/// @ret the ID
	ID_t getID();

	/// Returns the current value of the signal generated by this gait generator
	///
	/// @ret a shared pointer to a GaitSignal structure containing the current
	/// value of the signal
	std::shared_ptr<GaitSignal> readSignal();

protected:
	/// sends the signal of this generator to the rest of the architecture
	///
	/// @param pData a pointer to the value of the signal at the end of the
	/// current epoch
	void publishData(const std::shared_ptr<GaitSignal> &pData);

	const std::shared_ptr<const Dog> pRobot;	///< A pointer to the robot model
	const ID_t ID;								///< The ID of this gait generator
	const period_t period;						///< The period of this gait generator

private:
	// BEGIN critical section
		/// Signal generated by this gait generator
		///
		/// This member gets overwritten during the call to publishData. It can
		/// be read using readSignal. It is done this way so that anyone reading
		/// the signal from this generator will get a coherent view of the
		/// signal at the end of an epoch. Fields in the signal will not be from
		/// different epochs
		std::shared_ptr<GaitSignal> pData;
		std::mutex data_mutex;
	// END critical section
};

#endif /* end of include guard: GAIT_GENERATOR_HPP_5MDX0BG2 */
