/*******************************************************************************
*                                                       ,----,                 *
*                                                     .'   .' \                *
*                                                   ,----,'    |               *
*               ________  ___       ________        |    :  .  ;               *
*              |\   ___ \|\  \     |\   ____\       ;    |.'  /                *
*              \ \  \_|\ \ \  \    \ \  \___|_      `----'/  ;                 *
*               \ \  \ \\ \ \  \    \ \_____  \       /  ;  /                  *
*                \ \  \_\\ \ \  \____\|____|\  \     ;  /  /-,                 *
*                 \ \_______\ \_______\____\_\  \   /  /  /.`|                 *
*                  \|_______|\|_______|\_________\./__;      :                 *
*                                     \|_________||   :    .'                  *
*                                                 ;   | .'                     *
*                                                 `---'                        *
********************************************************************************
* Author:            Hendrik de Bruin                                          *
* Maintainer:        Hendrik de Bruin                                          *
* author email:      hendrik.debruin@iit.it                                    *
*******************************************************************************/
#ifndef GAIT_DATA_HPP_DLF4YRRS
#define GAIT_DATA_HPP_DLF4YRRS

#include "geometry/pose.hpp"
#include "todo.h"
#include <Eigen/Dense>
#include "msg/gait_signal.h"
#include "msg_wrappers/screw.hpp"

/// A structure containing the data streams that make up the signal at the
/// current time generated by a given gait generator
TODO("should this class be made thread safe?")
TODO("write test code to check the conversions of this class to rtps and back")
struct GaitSignal
{
	GaitSignal();
	TODO("read up if this should be reference or const or whatever")
	GaitSignal(GaitSignalMsg);
	operator GaitSignalMsg() const;

	TODO("can I use Pose class for velocities and accelerations?")
	TODO("handle default initialisations here")
	Pose desired_com_pose;			///< The desired pose of the center of mass frame
	Screw desired_com_velocity;		///< The desired velocity of the center of mass frame
	Screw desired_com_acceleration;	///< The desired accleration of the center of mass frame

	Pose desired_base_pose;			///< The desired pose of the base frame
	Screw desired_base_velocity;		///< The desired velocity of the base frame
	Screw desired_base_acceleration;	///< The desired acceleration of the base frame

	Eigen::VectorXd desired_joint_position;			///< The desired joint position
	Eigen::VectorXd desired_joint_velocity;			///< The desired joint velocity
	Eigen::VectorXd desired_joint_acceleration;		///< The desired joint acceleration

	Eigen::VectorXd desired_feed_forward_torque;	///< THe desired feed forard torque
	TODO("stance feet here")
};

#endif /* end of include guard: GAIT_DATA_HPP_DLF4YRRS */
