#ifndef GAIT_GENERATOR_HPP_5MDX0BG2
#define GAIT_GENERATOR_HPP_5MDX0BG2

#include "application_framework/components/app_layer_component.hpp"
#include "geometry/pose.hpp"

#include <mutex>
#include <memory>
#include <Eigen/Dense>

class Dog;
class GaitGenerator : public AppLayerComponent
{
protected:
	// TODO this is repeated in Controller. Refactor this into one location
	typedef std::chrono::duration<double, std::ratio<1, 1'000'000>> period_t;

	/// A structure containing the data streams that make up the signal
	/// generated by this gait generator
	// Todo should this be in a unifying location? Can its fields be read by
	// control layer or controller like this?
	struct DataOut
	{
		// TODO can I use Pose class for velocities and accelerations?
		Pose desired_com_pose;			///< The desired pose of the center of mass frame
		Pose desired_com_velocity;		///< The desired velocity of the center of mass frame
		Pose desired_com_acceleration;	///< The desired accleration of the center of mass frame

		Pose desired_base_pose;			///< The desired pose of the base frame
		Pose desired_base_velocity;		///< The desired velocity of the base frame
		Pose desired_base_acceleration;	///< The desired acceleration of the base frame

		Eigen::VectorXd desired_joint_state;			///< The desired joint state
		Eigen::VectorXd desired_joint_velocity;			///< The desired joint velocity
		Eigen::VectorXd desired_joint_acceleration;		///< The desired joint acceleration

		Eigen::VectorXd desired_feed_forward_torque;	///< THe desired feed forard torque
		// TODO stance feet here
	};

public:
	// Typedefs
	using ID_t = std::string;
	typedef GaitGenerator *create_t();
	typedef void destroy_t(GaitGenerator*);

	// Constructors
	GaitGenerator
	(
		const std::shared_ptr<Dog>&,	///< A pointer to the robot model
		const ID_t&,					///< The ID of the gait generator
		const period_t&					///< The period of the gait generator
	);

	virtual ~GaitGenerator() = default;

	/// Returns the ID of this gait generator
	///
	/// @ret the ID
	ID_t getID();

	/// Returns the current value of the signal generated by this gait generator
	///
	/// @ret a shared pointer to a DataOut structure containing the current
	/// value of the signal
	std::shared_ptr<DataOut> readSignal();

protected:
	/// sends the signal of this generator to the rest of the architecture
	///
	/// @param pData a pointer to the value of the signal at the end of the
	/// current epoch
	void publishData(const std::shared_ptr<DataOut> &pData);

	const std::shared_ptr<const Dog> pRobot;	///< A pointer to the robot model
	const ID_t ID;								///< The ID of this gait generator
	const period_t period;						///< The period of this gait generator

private:
	// BEGIN critical section
		/// Signal generated by this gait generator
		///
		/// This member gets overwritten during the call to publishData. It can
		/// be read using readSignal. It is done this way so that anyone reading
		/// the signal from this generator will get a coherent view of the
		/// signal at the end of an epoch. Fields in the signal will not be from
		/// different epochs
		std::shared_ptr<DataOut> pData;
		std::mutex data_mutex;
	// END critical section
};

#endif /* end of include guard: GAIT_GENERATOR_HPP_5MDX0BG2 */
