#ifndef GAIT_DATA_HPP_DLF4YRRS
#define GAIT_DATA_HPP_DLF4YRRS

#include "geometry/pose.hpp"
#include "todo.h"
#include <Eigen/Dense>

/// A structure containing the data streams that make up the signal at the
/// current time generated by a given gait generator
struct GaitSignal
{
	TODO("can I use Pose class for velocities and accelerations?")
	Pose desired_com_pose;			///< The desired pose of the center of mass frame
	Pose desired_com_velocity;		///< The desired velocity of the center of mass frame
	Pose desired_com_acceleration;	///< The desired accleration of the center of mass frame

	Pose desired_base_pose;			///< The desired pose of the base frame
	Pose desired_base_velocity;		///< The desired velocity of the base frame
	Pose desired_base_acceleration;	///< The desired acceleration of the base frame

	Eigen::VectorXd desired_joint_state;			///< The desired joint state
	Eigen::VectorXd desired_joint_velocity;			///< The desired joint velocity
	Eigen::VectorXd desired_joint_acceleration;		///< The desired joint acceleration

	Eigen::VectorXd desired_feed_forward_torque;	///< THe desired feed forard torque
	TODO("stance feet here")
};

#endif /* end of include guard: GAIT_DATA_HPP_DLF4YRRS */
