#ifndef GAIT_GENERATOR_HPP_5MDX0BG2
#define GAIT_GENERATOR_HPP_5MDX0BG2
// =============================================================================
// Includes
// =============================================================================
#include "application_framework/components/periodic_app_layer_component.hpp"
#include "gait_generator/gait_signal.hpp"
#include "todo.h"
#include "robot/robot.hpp"

#include <mutex>
#include <memory>
#include <atomic>

// fastrtps
#include <fastrtps/fastrtps_fwd.h>
#include <fastrtps/publisher/PublisherListener.h>
#include "msg/hello_worldPubSubTypes.h"

// =============================================================================
// Class Interface
// =============================================================================
class GaitGenerator : public PeriodicAppLayerComponent
{
protected:
	TODO("this is repeated in Controller. Refactor this into one location")
	typedef std::chrono::duration<double, std::ratio<1, 1'000'000>> period_t;

public:
	// Typedefs
	using ID_t = std::string;
	typedef GaitGenerator *create_t();
	typedef void destroy_t(GaitGenerator*);

	// Constructors
	GaitGenerator
	(
		const std::shared_ptr<Dog>&,	///< A pointer to the robot model
		const ID_t&,					///< The ID of the gait generator
		const period_t&					///< The period of the gait generator
	);

	virtual ~GaitGenerator() = default;
	/// Returns the ID of this gait generator
	///
	/// @ret the ID
	ID_t getID();

	/// Returns the current value of the signal generated by this gait generator
	///
	/// @ret a shared pointer to a GaitSignal structure containing the current
	/// value of the signal
	std::shared_ptr<GaitSignal> readSignal();

protected:
	/// sends the signal of this generator to the rest of the architecture
	///
	/// @param pData a pointer to the value of the signal at the end of the
	/// current epoch
	void publishData(const std::shared_ptr<GaitSignal> &pData);

	const std::shared_ptr<const Dog> pRobot;	///< A pointer to the robot model
	const ID_t ID;								///< The ID of this gait generator

private:
	// BEGIN critical section
		/// Signal generated by this gait generator
		///
		/// This member gets overwritten during the call to publishData. It can
		/// be read using readSignal. It is done this way so that anyone reading
		/// the signal from this generator will get a coherent view of the
		/// signal at the end of an epoch. Fields in the signal will not be from
		/// different epochs
		std::shared_ptr<GaitSignal> pData;
		std::mutex data_mutex;
	// END critical section

	// =============================== FastRTPS ================================
	std::shared_ptr<eprosima::fastrtps::Participant> pParticipant;
	std::shared_ptr<eprosima::fastrtps::Publisher> pPublisher;
	class PubListener : public eprosima::fastrtps::PublisherListener
	{
	public:
		PubListener() = default;
		~PubListener() = default;
	} listener;
	HelloWorldPubSubType rtps_type;
};

#endif /* end of include guard: GAIT_GENERATOR_HPP_5MDX0BG2 */
