<package format="2">
  <name>dls_hw_sim</name>
  <version>0.0.1</version>
  <description>
	This package contains the gazebo related files.
  </description>
  <maintainer email="a@iit.it">a</maintainer>

  <license>BSD</license>

  <author>a</author>

  <buildtool_depend>catkin</buildtool_depend>

  <depend>roscpp</depend> 
  <depend>gazebo_ros</depend>
  <depend>gazebo_ros_control</depend>
  <depend>controller_manager</depend> 
  <depend>pluginlib</depend> 
  <depend>transmission_interface</depend> 
  <depend>hardware_interface</depend> 
  <depend>dls2_hardware_interface</depend> 
  <depend>urdf</depend>
  <depend>realtime_tools</depend>
  <depend>dls_msgs</depend>

  <export>
	<gazebo_ros_control plugin="${prefix}/dls_hw_sim_plugins.xml"/>
  </export>

</package>


